# Dockerfile para el gateway
FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npx prisma generate --schema=/app/src/prisma/schema.prisma
RUN npm run build


EXPOSE 3003

# CMD final: migrar y arrancar app
CMD npx prisma generate --schema=/app/src/prisma/schema.prisma && npx prisma migrate reset --force --schema=/app/src/prisma/schema.prisma && npx prisma migrate dev --name init --schema=/app/src/prisma/schema.prisma && npx prisma migrate deploy --schema=/app/src/prisma/schema.prisma && npm run start:prod

