# FROM node:18-alpine AS builder

# # Set working directory
# WORKDIR /app

# # Install dependencies
# COPY package*.json ./
# RUN npm install

# # Copy source code
# COPY . .

# # Build the NestJS application
# RUN npm run build

# # Use a smaller base image for the production environment
# FROM node:18-alpine AS production


# # Ensure the entrypoint script is executable
# RUN chmod +x ./entrypoint.sh

# # Expose application port
# EXPOSE 3001
# EXPOSE 5432

# # Set the entrypoint
# ENTRYPOINT ["./entrypoint.sh"]

# Dockerfile para el gateway
FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npx prisma generate --schema=/app/src/prisma/schema.prisma
RUN npm run build
EXPOSE 3001

# CMD final: migrar y arrancar app
CMD npx prisma generate --schema=/app/src/prisma/schema.prisma && npx prisma migrate reset --force --schema=/app/src/prisma/schema.prisma && npx prisma migrate dev --name init --schema=/app/src/prisma/schema.prisma && npx prisma migrate deploy --schema=/app/src/prisma/schema.prisma && npm run start:prod

